<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>slam_robot_slam_3d</name>
  <version>0.1.0</version>
  <description>3D LiDAR odometry and online SLAM integration.</description>

  <maintainer email="dk.illidan@gmail.com">Jerry</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>libpcl-all-dev</build_depend>
  <build_export_depend>libpcl-all-dev</build_export_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>action_msgs</exec_depend>
  <depend>diagnostic_msgs</depend>
  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>libpcl-common</exec_depend>
  <exec_depend>libpcl-filters</exec_depend>
  <exec_depend>libpcl-kdtree</exec_depend>
  <exec_depend>libpcl-registration</exec_depend>
  <exec_depend>mola_bridge_ros2</exec_depend>
  <exec_depend>mola_lidar_odometry</exec_depend>
  <exec_depend>mola_metric_maps</exec_depend>
  <depend>nav_msgs</depend>
  <exec_depend>nav2_msgs</exec_depend>
  <depend>pcl_conversions</depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <depend>rclcpp</depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>
  <exec_depend>rtabmap_msgs</exec_depend>
  <exec_depend>rtabmap_rviz_plugins</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <depend>sensor_msgs</depend>
  <depend>slam_robot_slam</depend>
  <exec_depend>slam_robot_gazebo</exec_depend>
  <exec_depend>slam_robot_navigation</exec_depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <exec_depend>tf2_msgs</exec_depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
