<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>slam_robot_slam_3d</name>
  <version>0.1.0</version>
  <description>3D LiDAR odometry and online SLAM integration.</description>

  <maintainer email="dk.illidan@gmail.com">Jerry</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>mola_bridge_ros2</exec_depend>
  <exec_depend>mola_lidar_odometry</exec_depend>
  <exec_depend>mola_metric_maps</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rtabmap_rviz_plugins</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>slam_robot_gazebo</exec_depend>
  <exec_depend>slam_robot_navigation</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
